### PR TITLE
User signup and auth

### PR DESCRIPTION
**Pull request by ajm188**
Ok huge pull request here.

Contains:
- creation of user scaffold
- add clearance for authentication
- twitter-bootstrap for UI
- crap load of tests

Not all of the tests are implemented yet, but I figure this is enough work to get something merged in so other people can have something to work with.

Notable unimplemented tests:
- Anything involving mailers
- Password resets

### CODE REVIEW

**Comment by ajm188** [comment]
@StephHippo do you know if travis marks a build as failing if it has unimplemented tests?

**Comment by ajm188** [comment]
Tests are implemented now, so I take back what I said in my previous comment.

**Comment by ajm188** [comment]
@StephHippo files I changed after running rails g:
- app/controllers/users_controller.rb (specifically #create)
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
- app/views/user_mailer/

**Comment by StephHippo** [comment]
:+1: So proud of your tests. Good job.

**Pull request merged**
