### PR TITLE
JSON User API

### PR DESCRIPTION
**Pull request by ajm188**
The idea behind this PR is to start providing documentation for the JSON API we can serve to our iOS and andriod apps. It's also live documentation, so it should never be out of sync with the actual backend, which is cool.

### CODE REVIEW

**Comment by ajm188** [comment]
Alright, now that shit's actually working (floating points be damned), @StephHippo @gleichsnerd want to weigh in on this? Maybe @wasianish as well?

**Comment by gleichsnerd** [comment]
I completely forgot about including university info. Good catch.
Since we'll need some sort of authentication, have you thought about what password gem to use? bcrypt would be super simple to toss in there.

Also, gold star for that 98.28% coverage
goldstar

**Comment by ajm188** [comment]
Already have https://github.com/thoughtbot/clearance hooked up for auth. Investigating how to JSON-ify it right now. Also, shouldn't that be 9.828/10? :laughing:

**Comment by StephHippo** [comment]
Okay this was beautiful and I love that test coverage. :+1:

**Pull request merged**
